name: 'Build and Deploy to Cloud Run for Dev'

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # BEGIN - Docker auth and build
      #
      # If you already have a container image, you can omit these steps.
      - name: 'Docker Auth'
        run: gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: 'Build and Push Container'
        run: |-
          docker buildx build --platform linux/amd64 -t us-west1-docker.pkg.dev/alexkong-cdks2/my-repo/gcp-training-javascript .
          docker push us-west1-docker.pkg.dev/alexkong-cdks2/my-repo/gcp-training-javascript

      - name: 'Deploy to Cloud Run'

        # END - Docker auth and build

        run: gcloud run deploy gcp-training-javascript --image us-west1-docker.pkg.dev/alexkong-cdks2/my-repo/gcp-training-javascript:latest --region us-west1 --allow-unauthenticated

      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |2-

          echo ${{ steps.deploy.outputs.url }}
